version: '3.8'
services:
  db:
    image: 'mysql:8.0'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=movie_recommendation
      - MYSQL_ROOT_PASSWORD=yourpassword # Change this to your own password
    ports:
      - '3308:3306'
    volumes:
      - 'db:/var/lib/mysql'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
volumes:
  db:
    driver: local
