name: Format

on:
  push

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config user.name "Java Formatter - Livxy"
          git config user.email "<>"

      - name: Install Prettier
        run: npm i -g prettier@2.6.2

      - name: Run Prettier
        run: prettier -w **/*.java

      - name: Commit changes
        if: ${{ env.commit }} == 'true'
        run: |
          git diff-index --quiet HEAD
          if [ $? -ne 0 ]; then
            git add .
            git commit -m "Apply java formatting"
            git push
          else
            echo 'Nothing to commit!'
