name: Format

on:
  push

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Prettier
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-prettier-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-prettier-

      - name: Install Prettier
        run: npm i -g prettier@2.6.2
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Run Prettier
        run: prettier -w **/*.java

      - name: Commit changes
        if: ${{ env.commit }} == 'true'
        run: |
          git config user.name github-actions
          git config user.email ''
          git diff-index --quiet HEAD
          if [ $? -ne 0 ]; then
            git commit --all -m "${{ env.commitMessage }}"
            git push
          else
            echo 'Nothing to commit!'
          fi
