name: Format Java files

on:
  push:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Format Java code with Prettier
        uses: tsar-boomba/prettier-java-action@main
        with:
          prettier-args: "--write"
          files: "**/*.java"
          commit: true
          github-username: '📚'
          commit-message: "Apply Java formatting"
