name: Format

on:
  push

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Prettier
        run: |
          npm i -g prettier@2.6.2
          npm i -g prettier-plugin-java@1.6.1

      - name: Run Prettier
        run: prettier -w **/*.java

      - name: Commit changes
        if: ${{ env.commit }} == 'true'
        run: |
          git config user.name github-actions
          git config user.email ''
          git diff-index --quiet HEAD
          if [ $? -ne 0 ]; then
            git commit --all -m "${{ env.commitMessage }}"
            git push
          else
            echo 'Nothing to commit!'
          fi
