name: Format Java files

on:
  push:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git user name
        run: git config user.name "📚"

      - name: Format Java code with Prettier
        uses: tsar-boomba/prettier-java-action@v1.0.0
        with:
          prettier-args: "--write"
          files: "**/*.java"
          commit-message: "Apply Java formatting"
          commit: true
